/* advertisement_service_impl.cpp

 Generated by phxrpc_pb2service from ftrl.proto

*/

#include "advertisement_service_impl.h"

#include "phxrpc/file.h"

#include "advertisement_server_config.h"
#include "ftrl.pb.h"


using namespace std;


AdvertisementServiceImpl::AdvertisementServiceImpl(ServiceArgs_t &app_args) : args_(app_args) {
}

AdvertisementServiceImpl::~AdvertisementServiceImpl() {
}

int AdvertisementServiceImpl::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

int AdvertisementServiceImpl::Advertisement(const ftrl::AdvertisementRequest &req, ftrl::AdvertisementResult *resp) {
    return -1;
}

int AdvertisementServiceImpl::Feedback(const ftrl::AdvertisementFeedback &req, google::protobuf::Empty *resp) {
    return -1;
}

