/* advertisement_client.cpp

 Generated by phxrpc_pb2client from ftrl.proto

*/

#include "advertisement_client.h"

#include <cstdlib>
#include <memory>
#include <mutex>

#include "phxrpc/http.h"
#include "phxrpc/rpc.h"

#include "phxrpc_advertisement_stub.h"


using namespace std;


static phxrpc::ClientConfig global_advertisementclient_config_;
static phxrpc::ClientMonitorPtr global_advertisementclient_monitor_;


bool AdvertisementClient::Init(const char *config_file) {
    return global_advertisementclient_config_.Read(config_file);
}

const char *AdvertisementClient::GetPackageName() {
    const char *ret = global_advertisementclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "ftrl";
    }
    return ret;
}

AdvertisementClient::AdvertisementClient() {
    static mutex monitor_mutex;
    if (!global_advertisementclient_monitor_.get()) {
        monitor_mutex.lock();
        if (!global_advertisementclient_monitor_.get()) {
            global_advertisementclient_monitor_ = phxrpc::MonitorFactory::GetFactory()->
                    CreateClientMonitor(GetPackageName());
        }
        global_advertisementclient_config_.SetClientMonitor(global_advertisementclient_monitor_);
        monitor_mutex.unlock();
    }
}

AdvertisementClient::~AdvertisementClient() {
}

int AdvertisementClient::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp)
{
    const phxrpc::Endpoint_t *ep{global_advertisementclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_advertisementclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_advertisementclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_advertisementclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            AdvertisementStub stub(socket, *(global_advertisementclient_monitor_.get()), http_msg_factory);
            return stub.PHXEcho(req, resp);
        }

    }

    return -1;
}

int AdvertisementClient::PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp)
{
    int ret{-1};
    size_t echo_server_count{2};
    uthread_begin;
    for (size_t i{0}; echo_server_count > i; ++i) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t *ep = global_advertisementclient_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if (phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                    global_advertisementclient_config_.GetConnectTimeoutMS(), *(global_advertisementclient_monitor_.get()))) {
                    socket.SetTimeout(global_advertisementclient_config_.GetSocketTimeoutMS());
                    phxrpc::HttpMessageHandlerFactory http_msg_factory;
                    AdvertisementStub stub(socket, *(global_advertisementclient_monitor_.get()), http_msg_factory);
                    int this_ret{stub.PHXEcho(req, resp)};
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }
                }
            }
        };
    }
    uthread_end;
    return ret;
}

int AdvertisementClient::Advertisement(const ftrl::AdvertisementRequest &req, ftrl::AdvertisementResult *resp)
{
    const phxrpc::Endpoint_t *ep{global_advertisementclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_advertisementclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_advertisementclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_advertisementclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            AdvertisementStub stub(socket, *(global_advertisementclient_monitor_.get()), http_msg_factory);
            return stub.Advertisement(req, resp);
        }

    }

    return -1;
}

int AdvertisementClient::Feedback(const ftrl::AdvertisementFeedback &req, google::protobuf::Empty *resp)
{
    const phxrpc::Endpoint_t *ep{global_advertisementclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_advertisementclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_advertisementclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_advertisementclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            AdvertisementStub stub(socket, *(global_advertisementclient_monitor_.get()), http_msg_factory);
            return stub.Feedback(req, resp);
        }

    }

    return -1;
}

