/* advertisement_server_config.h

 Generated by phxrpc_pb2server from ftrl.proto

*/

#pragma once

#include "phxrpc/rpc.h"


class AdvertisementServerConfig {
  public:
    AdvertisementServerConfig();

    virtual ~AdvertisementServerConfig();

    bool Read(const char *config_file);

    phxrpc::HshaServerConfig &GetHshaServerConfig();

  private:
    phxrpc::HshaServerConfig ep_server_config_;
};

