/* advertisement_tool_impl.h

 Generated by phxrpc_pb2tool from ftrl.proto

*/

#pragma once

#include "phxrpc_advertisement_tool.h"


namespace phxrpc {


class OptMap;


}


class AdvertisementToolImpl : public AdvertisementTool {
  public:
    AdvertisementToolImpl();
    virtual ~AdvertisementToolImpl() override;

    virtual int PHXEcho(phxrpc::OptMap &opt_map) override;
    virtual int Advertisement(phxrpc::OptMap &opt_map) override;
    virtual int Feedback(phxrpc::OptMap &opt_map) override;
};

