/* advertisement_service_impl.h

 Generated by phxrpc_pb2service from ftrl.proto

*/

#pragma once

#include "ftrl.pb.h"
#include "phxrpc_advertisement_service.h"


class AdvertisementServerConfig;

typedef struct tagServiceArgs {
    AdvertisementServerConfig *config;
    // you can add other arguments here and initiate in main().
} ServiceArgs_t;

class AdvertisementServiceImpl : public AdvertisementService {
  public:
    AdvertisementServiceImpl(ServiceArgs_t &app_args);
    virtual ~AdvertisementServiceImpl() override;

    virtual int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) override;
    virtual int Advertisement(const ftrl::AdvertisementRequest &req, ftrl::AdvertisementResult *resp) override;
    virtual int Feedback(const ftrl::AdvertisementFeedback &req, google::protobuf::Empty *resp) override;

  private:
    ServiceArgs_t &args_;
};

