/* advertisement_client.h

 Generated by phxrpc_pb2client from ftrl.proto

*/

#pragma once

#include "ftrl.pb.h"
#include "phxrpc/rpc.h"


class AdvertisementClient {
  public:
    static bool Init(const char *config_file);

    static const char *GetPackageName();

    AdvertisementClient();
    virtual ~AdvertisementClient();

    int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int Advertisement(const ftrl::AdvertisementRequest &req, ftrl::AdvertisementResult *resp);
    int Feedback(const ftrl::AdvertisementFeedback &req, google::protobuf::Empty *resp);
};

