/* advertisement_service_impl.cpp

 Generated by phxrpc_pb2service from ftrl.proto

*/

#include "advertisement_service_impl.h"

#include "phxrpc/file.h"

#include "advertisement_server_config.h"
#include "ftrl.pb.h"
#include <sys/ipc.h>
#include <sys/shm.h>

#define SHM_KEY 0x1234

struct shmseg {
    int mode; //0: user_id ready, 1: ad_id ready, 2:feedback ready
    long long user_id;
    long long ad_id;
    bool feedback; 
};

::google::protobuf::int64 RequestAdId(::google::protobuf::int64 user_id){
	int shmid;
    shmid = shmget(SHM_KEY, sizeof(struct shmseg), 0644|IPC_CREAT);
    if (shmid == -1) {
      perror("Shared memory");
      return 1;
    }

    shmseg *shmp;

    shmp = (struct shmseg*) shmat(shmid, NULL, 0);
    if (shmp == (void *) -1) {
        perror("Shared memory attach");
        return 1;
    }

    while(shmp->mode != -1){
        //waiting
    }

    shmp->user_id = (long long) user_id;

    shmp->mode = 0;

    while(shmp->mode != 1){
        //waiting for result
    }

    return (::google::protobuf::int64)shmp->ad_id;


}

void SendFeedback(::google::protobuf::int64 ad_id, int feedback){
	int shmid;
    shmid = shmget(SHM_KEY, sizeof(struct shmseg), 0644|IPC_CREAT);
    if (shmid == -1) {
      perror("Shared memory");
      return 1;
    }

    shmseg *shmp;

    shmp = (struct shmseg*) shmat(shmid, NULL, 0);
    if (shmp == (void *) -1) {
        perror("Shared memory attach");
        return 1;
    }

    while(shmp->mode != -1){
        //waiting
    }

    shmp->ad_id = (long long) ad_id;
    shmp->feedback = feedback;
    shmp->mode = 2;

    return;
}

AdvertisementServiceImpl::AdvertisementServiceImpl(ServiceArgs_t &app_args) : args_(app_args) {
}

AdvertisementServiceImpl::~AdvertisementServiceImpl() {
}

int AdvertisementServiceImpl::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    resp->set_value(req.value());
    return 0;
}

int AdvertisementServiceImpl::Advertisement(const ftrl::AdvertisementRequest &req, ftrl::AdvertisementResult *resp) {
    ::google::protobuf::int64 ad_id = RequestAdId(req.user_id());//to be implemented
    resp->set_ad_id((::google::protobuf::int64) ad_id);
    return 0;
}

int AdvertisementServiceImpl::Feedback(const ftrl::AdvertisementFeedback &req, google::protobuf::Empty *resp) {
    SendFeedback(req.ad_id(),req.feedback());
    return 0;
}

