// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ftrl.proto

#ifndef PROTOBUF_ftrl_2eproto__INCLUDED
#define PROTOBUF_ftrl_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/wrappers.pb.h>
#include <google/protobuf/empty.pb.h>
#include "phxrpc/rpc/phxrpc.pb.h"
// @@protoc_insertion_point(includes)

namespace ftrl {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_ftrl_2eproto();
void protobuf_AssignDesc_ftrl_2eproto();
void protobuf_ShutdownFile_ftrl_2eproto();

class AdvertisementFeedback;
class AdvertisementRequest;
class AdvertisementResult;

// ===================================================================

class AdvertisementRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ftrl.AdvertisementRequest) */ {
 public:
  AdvertisementRequest();
  virtual ~AdvertisementRequest();

  AdvertisementRequest(const AdvertisementRequest& from);

  inline AdvertisementRequest& operator=(const AdvertisementRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdvertisementRequest& default_instance();

  void Swap(AdvertisementRequest* other);

  // implements Message ----------------------------------------------

  inline AdvertisementRequest* New() const { return New(NULL); }

  AdvertisementRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AdvertisementRequest& from);
  void MergeFrom(const AdvertisementRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AdvertisementRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::google::protobuf::int64 user_id() const;
  void set_user_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ftrl.AdvertisementRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 user_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ftrl_2eproto();
  friend void protobuf_AssignDesc_ftrl_2eproto();
  friend void protobuf_ShutdownFile_ftrl_2eproto();

  void InitAsDefaultInstance();
  static AdvertisementRequest* default_instance_;
};
// -------------------------------------------------------------------

class AdvertisementResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ftrl.AdvertisementResult) */ {
 public:
  AdvertisementResult();
  virtual ~AdvertisementResult();

  AdvertisementResult(const AdvertisementResult& from);

  inline AdvertisementResult& operator=(const AdvertisementResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdvertisementResult& default_instance();

  void Swap(AdvertisementResult* other);

  // implements Message ----------------------------------------------

  inline AdvertisementResult* New() const { return New(NULL); }

  AdvertisementResult* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AdvertisementResult& from);
  void MergeFrom(const AdvertisementResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AdvertisementResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 ad_id = 1;
  void clear_ad_id();
  static const int kAdIdFieldNumber = 1;
  ::google::protobuf::int64 ad_id() const;
  void set_ad_id(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ftrl.AdvertisementResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 ad_id_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ftrl_2eproto();
  friend void protobuf_AssignDesc_ftrl_2eproto();
  friend void protobuf_ShutdownFile_ftrl_2eproto();

  void InitAsDefaultInstance();
  static AdvertisementResult* default_instance_;
};
// -------------------------------------------------------------------

class AdvertisementFeedback : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ftrl.AdvertisementFeedback) */ {
 public:
  AdvertisementFeedback();
  virtual ~AdvertisementFeedback();

  AdvertisementFeedback(const AdvertisementFeedback& from);

  inline AdvertisementFeedback& operator=(const AdvertisementFeedback& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AdvertisementFeedback& default_instance();

  void Swap(AdvertisementFeedback* other);

  // implements Message ----------------------------------------------

  inline AdvertisementFeedback* New() const { return New(NULL); }

  AdvertisementFeedback* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AdvertisementFeedback& from);
  void MergeFrom(const AdvertisementFeedback& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AdvertisementFeedback* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 ad_id = 1;
  void clear_ad_id();
  static const int kAdIdFieldNumber = 1;
  ::google::protobuf::int64 ad_id() const;
  void set_ad_id(::google::protobuf::int64 value);

  // optional bool feedback = 2;
  void clear_feedback();
  static const int kFeedbackFieldNumber = 2;
  bool feedback() const;
  void set_feedback(bool value);

  // @@protoc_insertion_point(class_scope:ftrl.AdvertisementFeedback)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int64 ad_id_;
  bool feedback_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ftrl_2eproto();
  friend void protobuf_AssignDesc_ftrl_2eproto();
  friend void protobuf_ShutdownFile_ftrl_2eproto();

  void InitAsDefaultInstance();
  static AdvertisementFeedback* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// AdvertisementRequest

// optional int64 user_id = 1;
inline void AdvertisementRequest::clear_user_id() {
  user_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 AdvertisementRequest::user_id() const {
  // @@protoc_insertion_point(field_get:ftrl.AdvertisementRequest.user_id)
  return user_id_;
}
inline void AdvertisementRequest::set_user_id(::google::protobuf::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:ftrl.AdvertisementRequest.user_id)
}

// -------------------------------------------------------------------

// AdvertisementResult

// optional int64 ad_id = 1;
inline void AdvertisementResult::clear_ad_id() {
  ad_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 AdvertisementResult::ad_id() const {
  // @@protoc_insertion_point(field_get:ftrl.AdvertisementResult.ad_id)
  return ad_id_;
}
inline void AdvertisementResult::set_ad_id(::google::protobuf::int64 value) {
  
  ad_id_ = value;
  // @@protoc_insertion_point(field_set:ftrl.AdvertisementResult.ad_id)
}

// -------------------------------------------------------------------

// AdvertisementFeedback

// optional int64 ad_id = 1;
inline void AdvertisementFeedback::clear_ad_id() {
  ad_id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 AdvertisementFeedback::ad_id() const {
  // @@protoc_insertion_point(field_get:ftrl.AdvertisementFeedback.ad_id)
  return ad_id_;
}
inline void AdvertisementFeedback::set_ad_id(::google::protobuf::int64 value) {
  
  ad_id_ = value;
  // @@protoc_insertion_point(field_set:ftrl.AdvertisementFeedback.ad_id)
}

// optional bool feedback = 2;
inline void AdvertisementFeedback::clear_feedback() {
  feedback_ = false;
}
inline bool AdvertisementFeedback::feedback() const {
  // @@protoc_insertion_point(field_get:ftrl.AdvertisementFeedback.feedback)
  return feedback_;
}
inline void AdvertisementFeedback::set_feedback(bool value) {
  
  feedback_ = value;
  // @@protoc_insertion_point(field_set:ftrl.AdvertisementFeedback.feedback)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ftrl

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ftrl_2eproto__INCLUDED
