/* ftrl_client.cpp

 Generated by phxrpc_pb2client from ftrl.proto

*/

#include "ftrl_client.h"

#include <cstdlib>
#include <memory>
#include <mutex>

#include "phxrpc/http.h"
#include "phxrpc/rpc.h"

#include "phxrpc_ftrl_stub.h"


using namespace std;


static phxrpc::ClientConfig global_ftrlclient_config_;
static phxrpc::ClientMonitorPtr global_ftrlclient_monitor_;


bool FTRLClient::Init(const char *config_file) {
    return global_ftrlclient_config_.Read(config_file);
}

const char *FTRLClient::GetPackageName() {
    const char *ret = global_ftrlclient_config_.GetPackageName();
    if (strlen(ret) == 0) {
        ret = "ftrl";
    }
    return ret;
}

FTRLClient::FTRLClient() {
    static mutex monitor_mutex;
    if (!global_ftrlclient_monitor_.get()) {
        monitor_mutex.lock();
        if (!global_ftrlclient_monitor_.get()) {
            global_ftrlclient_monitor_ = phxrpc::MonitorFactory::GetFactory()->
                    CreateClientMonitor(GetPackageName());
        }
        global_ftrlclient_config_.SetClientMonitor(global_ftrlclient_monitor_);
        monitor_mutex.unlock();
    }
}

FTRLClient::~FTRLClient() {
}

int FTRLClient::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp)
{
    const phxrpc::Endpoint_t *ep{global_ftrlclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_ftrlclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_ftrlclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_ftrlclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            FTRLStub stub(socket, *(global_ftrlclient_monitor_.get()), http_msg_factory);
            return stub.PHXEcho(req, resp);
        }

    }

    return -1;
}

int FTRLClient::PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp)
{
    int ret{-1};
    size_t echo_server_count{2};
    uthread_begin;
    for (size_t i{0}; echo_server_count > i; ++i) {
        uthread_t [=, &uthread_s, &ret](void *) {
            const phxrpc::Endpoint_t *ep = global_ftrlclient_config_.GetByIndex(i);
            if (ep != nullptr) {
                phxrpc::UThreadTcpStream socket;
                if (phxrpc::PhxrpcTcpUtils::Open(&uthread_s, &socket, ep->ip, ep->port,
                    global_ftrlclient_config_.GetConnectTimeoutMS(), *(global_ftrlclient_monitor_.get()))) {
                    socket.SetTimeout(global_ftrlclient_config_.GetSocketTimeoutMS());
                    phxrpc::HttpMessageHandlerFactory http_msg_factory;
                    FTRLStub stub(socket, *(global_ftrlclient_monitor_.get()), http_msg_factory);
                    int this_ret{stub.PHXEcho(req, resp)};
                    if (this_ret == 0) {
                        ret = this_ret;
                        uthread_s.Close();
                    }
                }
            }
        };
    }
    uthread_end;
    return ret;
}

int FTRLClient::FTRL(const ftrl::FTRLRequest &req, ftrl::FTRLResult *resp)
{
    const phxrpc::Endpoint_t *ep{global_ftrlclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_ftrlclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_ftrlclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_ftrlclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            FTRLStub stub(socket, *(global_ftrlclient_monitor_.get()), http_msg_factory);
            return stub.FTRL(req, resp);
        }

    }

    return -1;
}

int FTRLClient::Feedback(const ftrl::FTRLFeedback &req, google::protobuf::Empty *resp)
{
    const phxrpc::Endpoint_t *ep{global_ftrlclient_config_.GetRandom()};

    if (ep) {
        phxrpc::BlockTcpStream socket;
        bool open_ret{phxrpc::PhxrpcTcpUtils::Open(&socket, ep->ip, ep->port,
                global_ftrlclient_config_.GetConnectTimeoutMS(), nullptr, 0,
                *(global_ftrlclient_monitor_.get()))};
        if (open_ret) {
            socket.SetTimeout(global_ftrlclient_config_.GetSocketTimeoutMS());
            phxrpc::HttpMessageHandlerFactory http_msg_factory;
            FTRLStub stub(socket, *(global_ftrlclient_monitor_.get()), http_msg_factory);
            return stub.Feedback(req, resp);
        }

    }

    return -1;
}

