/* ftrl_client.h

 Generated by phxrpc_pb2client from ftrl.proto

*/

#pragma once

#include "ftrl.pb.h"
#include "phxrpc/rpc.h"


class FTRLClient {
  public:
    static bool Init(const char *config_file);

    static const char *GetPackageName();

    FTRLClient();
    virtual ~FTRLClient();

    int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int PHXBatchEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    int FTRL(const ftrl::FTRLRequest &req, ftrl::FTRLResult *resp);
    int Feedback(const ftrl::FTRLFeedback &req, google::protobuf::Empty *resp);
};

