/* ftrl_tool_impl.h

 Generated by phxrpc_pb2tool from ftrl.proto

*/

#pragma once

#include "phxrpc_ftrl_tool.h"


namespace phxrpc {


class OptMap;


}


class FTRLToolImpl : public FTRLTool {
  public:
    FTRLToolImpl();
    virtual ~FTRLToolImpl() override;

    virtual int PHXEcho(phxrpc::OptMap &opt_map) override;
    virtual int FTRL(phxrpc::OptMap &opt_map) override;
    virtual int Feedback(phxrpc::OptMap &opt_map) override;
};

