// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ftrl.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ftrl_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ftrl_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3008000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3008000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/wrappers.pb.h>
#include <google/protobuf/empty.pb.h>
#include "phxrpc/rpc/phxrpc.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ftrl_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ftrl_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ftrl_2eproto;
namespace ftrl {
class AdvertisementFeedback;
class AdvertisementFeedbackDefaultTypeInternal;
extern AdvertisementFeedbackDefaultTypeInternal _AdvertisementFeedback_default_instance_;
class AdvertisementRequest;
class AdvertisementRequestDefaultTypeInternal;
extern AdvertisementRequestDefaultTypeInternal _AdvertisementRequest_default_instance_;
class AdvertisementResult;
class AdvertisementResultDefaultTypeInternal;
extern AdvertisementResultDefaultTypeInternal _AdvertisementResult_default_instance_;
}  // namespace ftrl
PROTOBUF_NAMESPACE_OPEN
template<> ::ftrl::AdvertisementFeedback* Arena::CreateMaybeMessage<::ftrl::AdvertisementFeedback>(Arena*);
template<> ::ftrl::AdvertisementRequest* Arena::CreateMaybeMessage<::ftrl::AdvertisementRequest>(Arena*);
template<> ::ftrl::AdvertisementResult* Arena::CreateMaybeMessage<::ftrl::AdvertisementResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ftrl {

// ===================================================================

class AdvertisementRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ftrl.AdvertisementRequest) */ {
 public:
  AdvertisementRequest();
  virtual ~AdvertisementRequest();

  AdvertisementRequest(const AdvertisementRequest& from);
  AdvertisementRequest(AdvertisementRequest&& from) noexcept
    : AdvertisementRequest() {
    *this = ::std::move(from);
  }

  inline AdvertisementRequest& operator=(const AdvertisementRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline AdvertisementRequest& operator=(AdvertisementRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AdvertisementRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AdvertisementRequest* internal_default_instance() {
    return reinterpret_cast<const AdvertisementRequest*>(
               &_AdvertisementRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AdvertisementRequest* other);
  friend void swap(AdvertisementRequest& a, AdvertisementRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AdvertisementRequest* New() const final {
    return CreateMaybeMessage<AdvertisementRequest>(nullptr);
  }

  AdvertisementRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AdvertisementRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AdvertisementRequest& from);
  void MergeFrom(const AdvertisementRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AdvertisementRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ftrl.AdvertisementRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ftrl_2eproto);
    return ::descriptor_table_ftrl_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int64 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value);

  // @@protoc_insertion_point(class_scope:ftrl.AdvertisementRequest)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int64 user_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ftrl_2eproto;
};
// -------------------------------------------------------------------

class AdvertisementResult :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ftrl.AdvertisementResult) */ {
 public:
  AdvertisementResult();
  virtual ~AdvertisementResult();

  AdvertisementResult(const AdvertisementResult& from);
  AdvertisementResult(AdvertisementResult&& from) noexcept
    : AdvertisementResult() {
    *this = ::std::move(from);
  }

  inline AdvertisementResult& operator=(const AdvertisementResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline AdvertisementResult& operator=(AdvertisementResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AdvertisementResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AdvertisementResult* internal_default_instance() {
    return reinterpret_cast<const AdvertisementResult*>(
               &_AdvertisementResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(AdvertisementResult* other);
  friend void swap(AdvertisementResult& a, AdvertisementResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AdvertisementResult* New() const final {
    return CreateMaybeMessage<AdvertisementResult>(nullptr);
  }

  AdvertisementResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AdvertisementResult>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AdvertisementResult& from);
  void MergeFrom(const AdvertisementResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AdvertisementResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ftrl.AdvertisementResult";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ftrl_2eproto);
    return ::descriptor_table_ftrl_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 ad_id = 1;
  void clear_ad_id();
  static const int kAdIdFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int64 ad_id() const;
  void set_ad_id(::PROTOBUF_NAMESPACE_ID::int64 value);

  // @@protoc_insertion_point(class_scope:ftrl.AdvertisementResult)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int64 ad_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ftrl_2eproto;
};
// -------------------------------------------------------------------

class AdvertisementFeedback :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ftrl.AdvertisementFeedback) */ {
 public:
  AdvertisementFeedback();
  virtual ~AdvertisementFeedback();

  AdvertisementFeedback(const AdvertisementFeedback& from);
  AdvertisementFeedback(AdvertisementFeedback&& from) noexcept
    : AdvertisementFeedback() {
    *this = ::std::move(from);
  }

  inline AdvertisementFeedback& operator=(const AdvertisementFeedback& from) {
    CopyFrom(from);
    return *this;
  }
  inline AdvertisementFeedback& operator=(AdvertisementFeedback&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const AdvertisementFeedback& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AdvertisementFeedback* internal_default_instance() {
    return reinterpret_cast<const AdvertisementFeedback*>(
               &_AdvertisementFeedback_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(AdvertisementFeedback* other);
  friend void swap(AdvertisementFeedback& a, AdvertisementFeedback& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AdvertisementFeedback* New() const final {
    return CreateMaybeMessage<AdvertisementFeedback>(nullptr);
  }

  AdvertisementFeedback* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<AdvertisementFeedback>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const AdvertisementFeedback& from);
  void MergeFrom(const AdvertisementFeedback& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AdvertisementFeedback* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ftrl.AdvertisementFeedback";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ftrl_2eproto);
    return ::descriptor_table_ftrl_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 user_id = 1;
  void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::int64 user_id() const;
  void set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value);

  // int64 ad_id = 2;
  void clear_ad_id();
  static const int kAdIdFieldNumber = 2;
  ::PROTOBUF_NAMESPACE_ID::int64 ad_id() const;
  void set_ad_id(::PROTOBUF_NAMESPACE_ID::int64 value);

  // bool feedback = 3;
  void clear_feedback();
  static const int kFeedbackFieldNumber = 3;
  bool feedback() const;
  void set_feedback(bool value);

  // @@protoc_insertion_point(class_scope:ftrl.AdvertisementFeedback)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int64 user_id_;
  ::PROTOBUF_NAMESPACE_ID::int64 ad_id_;
  bool feedback_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_ftrl_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AdvertisementRequest

// int64 user_id = 1;
inline void AdvertisementRequest::clear_user_id() {
  user_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 AdvertisementRequest::user_id() const {
  // @@protoc_insertion_point(field_get:ftrl.AdvertisementRequest.user_id)
  return user_id_;
}
inline void AdvertisementRequest::set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:ftrl.AdvertisementRequest.user_id)
}

// -------------------------------------------------------------------

// AdvertisementResult

// int64 ad_id = 1;
inline void AdvertisementResult::clear_ad_id() {
  ad_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 AdvertisementResult::ad_id() const {
  // @@protoc_insertion_point(field_get:ftrl.AdvertisementResult.ad_id)
  return ad_id_;
}
inline void AdvertisementResult::set_ad_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  ad_id_ = value;
  // @@protoc_insertion_point(field_set:ftrl.AdvertisementResult.ad_id)
}

// -------------------------------------------------------------------

// AdvertisementFeedback

// int64 user_id = 1;
inline void AdvertisementFeedback::clear_user_id() {
  user_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 AdvertisementFeedback::user_id() const {
  // @@protoc_insertion_point(field_get:ftrl.AdvertisementFeedback.user_id)
  return user_id_;
}
inline void AdvertisementFeedback::set_user_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  user_id_ = value;
  // @@protoc_insertion_point(field_set:ftrl.AdvertisementFeedback.user_id)
}

// int64 ad_id = 2;
inline void AdvertisementFeedback::clear_ad_id() {
  ad_id_ = PROTOBUF_LONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::int64 AdvertisementFeedback::ad_id() const {
  // @@protoc_insertion_point(field_get:ftrl.AdvertisementFeedback.ad_id)
  return ad_id_;
}
inline void AdvertisementFeedback::set_ad_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  
  ad_id_ = value;
  // @@protoc_insertion_point(field_set:ftrl.AdvertisementFeedback.ad_id)
}

// bool feedback = 3;
inline void AdvertisementFeedback::clear_feedback() {
  feedback_ = false;
}
inline bool AdvertisementFeedback::feedback() const {
  // @@protoc_insertion_point(field_get:ftrl.AdvertisementFeedback.feedback)
  return feedback_;
}
inline void AdvertisementFeedback::set_feedback(bool value) {
  
  feedback_ = value;
  // @@protoc_insertion_point(field_set:ftrl.AdvertisementFeedback.feedback)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ftrl

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ftrl_2eproto
