/* ftrl_service_impl.h

 Generated by phxrpc_pb2service from ftrl.proto

*/

#pragma once

#include "ftrl.pb.h"
#include "phxrpc_ftrl_service.h"


class FTRLServerConfig;

typedef struct tagServiceArgs {
    FTRLServerConfig *config;
    // you can add other arguments here and initiate in main().
} ServiceArgs_t;

class FTRLServiceImpl : public FTRLService {
  public:
    FTRLServiceImpl(ServiceArgs_t &app_args);
    virtual ~FTRLServiceImpl() override;

    virtual int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) override;
    virtual int FTRL(const ftrl::FTRLRequest &req, ftrl::FTRLResult *resp) override;
    virtual int Feedback(const ftrl::FTRLFeedback &req, google::protobuf::Empty *resp) override;

  private:
    ServiceArgs_t &args_;
};

