/* phxrpc_advertisement_dispatcher.h

 Generated by phxrpc_pb2service from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_advertisement_dispatcher.h"

#include <errno.h>

#include "phxrpc/http.h"
#include "phxrpc/file.h"

#include "ftrl.pb.h"
#include "phxrpc_advertisement_service.h"


AdvertisementDispatcher::AdvertisementDispatcher(AdvertisementService &service, phxrpc::DispatcherArgs_t *dispatcher_args)
        : service_(service), dispatcher_args_(dispatcher_args) {
}

AdvertisementDispatcher::~AdvertisementDispatcher() {
}

const phxrpc::BaseDispatcher<AdvertisementDispatcher>::URIFuncMap &AdvertisementDispatcher::GetURIFuncMap() {
    static phxrpc::BaseDispatcher<AdvertisementDispatcher>::URIFuncMap uri_func_map = {
        {"/ftrl/PHXEcho", &AdvertisementDispatcher::PHXEcho},
        {"/ftrl/Advertisement", &AdvertisementDispatcher::Advertisement},
        {"/ftrl/Feedback", &AdvertisementDispatcher::Feedback}};
    return uri_func_map;
}

int AdvertisementDispatcher::PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(-1, "PHXEcho", 1);

    int ret{-1};

    google::protobuf::StringValue req_pb;
    google::protobuf::StringValue resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.PHXEcho(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: PHXEcho = %d", ret);

    return ret;
}

int AdvertisementDispatcher::Advertisement(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(1, "Advertisement", 1);

    int ret{-1};

    ftrl::AdvertisementRequest req_pb;
    ftrl::AdvertisementResult resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.Advertisement(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: Advertisement = %d", ret);

    return ret;
}

int AdvertisementDispatcher::Feedback(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(2, "Feedback", 1);

    int ret{-1};

    ftrl::AdvertisementFeedback req_pb;
    google::protobuf::Empty resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.Feedback(req_pb, &resp_pb);
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: Feedback = %d", ret);

    return ret;
}

