/* phxrpc_ftrl_tool.h

 Generated by phxrpc_pb2tool from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once


namespace phxrpc {


class OptMap;


}


class FTRLTool {
  public:
    FTRLTool();
    virtual ~FTRLTool();

    virtual int PHXEcho(phxrpc::OptMap &bigmap);
    virtual int FTRL(phxrpc::OptMap &bigmap);
    virtual int Feedback(phxrpc::OptMap &bigmap);

    typedef int (FTRLTool::*ToolFunc_t)(phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        FTRLTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            {"PHXEcho", &FTRLTool::PHXEcho, "c:f:vs:",
                    "-s <string>"},
            {"FTRL", &FTRLTool::FTRL, "c:f:vu:",
                    "-u <user_id>"},
            {"Feedback", &FTRLTool::Feedback, "c:f:vu: a: r:",
                    "-u <user_id> -a <ad_id> -r <feedback>"},
            {nullptr, nullptr}
        };

        return name2func;
    };
};

