/* phxrpc_advertisement_dispatcher.h

 Generated by phxrpc_pb2service from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "phxrpc/rpc.h"


class AdvertisementService;

class AdvertisementDispatcher {
  public:
    static const phxrpc::BaseDispatcher<AdvertisementDispatcher>::URIFuncMap &GetURIFuncMap();

    AdvertisementDispatcher(AdvertisementService &service, phxrpc::DispatcherArgs_t *dispatcher_args);

    virtual ~AdvertisementDispatcher();

    int PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int Advertisement(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int Feedback(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);

  private:
    AdvertisementService &service_;
    phxrpc::DispatcherArgs_t *dispatcher_args_;
};

