/* phxrpc_advertisement_service.cpp

 Generated by phxrpc_pb2service from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_advertisement_service.h"

#include "ftrl.pb.h"
#include "phxrpc/file.h"


AdvertisementService::AdvertisementService() {
}

AdvertisementService::~AdvertisementService() {
}

int AdvertisementService::PHXEcho(const google::protobuf::StringValue &/* req */, google::protobuf::StringValue */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: PHXEcho unimplemented");
    return -1;
}

int AdvertisementService::Advertisement(const ftrl::AdvertisementRequest &/* req */, ftrl::AdvertisementResult */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: Advertisement unimplemented");
    return -1;
}

int AdvertisementService::Feedback(const ftrl::AdvertisementFeedback &/* req */, google::protobuf::Empty */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: Feedback unimplemented");
    return -1;
}

