/* phxrpc_advertisement_tool.h

 Generated by phxrpc_pb2tool from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once


namespace phxrpc {


class OptMap;


}


class AdvertisementTool {
  public:
    AdvertisementTool();
    virtual ~AdvertisementTool();

    virtual int PHXEcho(phxrpc::OptMap &bigmap);
    virtual int Advertisement(phxrpc::OptMap &bigmap);
    virtual int Feedback(phxrpc::OptMap &bigmap);

    typedef int (AdvertisementTool::*ToolFunc_t)(phxrpc::OptMap &);

    typedef struct tagName2Func {
        const char *name;
        AdvertisementTool::ToolFunc_t func;
        const char *opt_string;
        const char *usage;
    } Name2Func_t;

    static Name2Func_t *GetName2Func() {
        static Name2Func_t name2func[]{
            {"PHXEcho", &AdvertisementTool::PHXEcho, "c:f:vs:",
                    "-s <string>"},
            {"Advertisement", &AdvertisementTool::Advertisement, "c:f:vu:",
                    "-u <user_id>"},
            {"Feedback", &AdvertisementTool::Feedback, "c:f:vad: f:",
                    "-ad <advertisement_id> -f <feedback>"},
            {nullptr, nullptr}
        };

        return name2func;
    };
};

