/* phxrpc_ftrl_service.cpp

 Generated by phxrpc_pb2service from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_ftrl_service.h"

#include "ftrl.pb.h"
#include "phxrpc/file.h"


FTRLService::FTRLService() {
}

FTRLService::~FTRLService() {
}

int FTRLService::PHXEcho(const google::protobuf::StringValue &/* req */, google::protobuf::StringValue */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: PHXEcho unimplemented");
    return -1;
}

int FTRLService::FTRL(const ftrl::FTRLRequest &/* req */, ftrl::FTRLResult */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: FTRL unimplemented");
    return -1;
}

int FTRLService::Feedback(const ftrl::FTRLFeedback &/* req */, google::protobuf::Empty */* resp */) {
    phxrpc::log(LOG_ERR, "ERROR: Feedback unimplemented");
    return -1;
}

