/* phxrpc_ftrl_dispatcher.h

 Generated by phxrpc_pb2service from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_ftrl_dispatcher.h"

#include <errno.h>

#include "phxrpc/http.h"
#include "phxrpc/file.h"

#include "ftrl.pb.h"
#include "phxrpc_ftrl_service.h"


FTRLDispatcher::FTRLDispatcher(FTRLService &service, phxrpc::DispatcherArgs_t *dispatcher_args)
        : service_(service), dispatcher_args_(dispatcher_args) {
}

FTRLDispatcher::~FTRLDispatcher() {
}

const phxrpc::BaseDispatcher<FTRLDispatcher>::URIFuncMap &FTRLDispatcher::GetURIFuncMap() {
    static phxrpc::BaseDispatcher<FTRLDispatcher>::URIFuncMap uri_func_map = {
        {"/ftrl/PHXEcho", &FTRLDispatcher::PHXEcho},
        {"/ftrl/FTRL", &FTRLDispatcher::FTRL},
        {"/ftrl/Feedback", &FTRLDispatcher::Feedback}};
    return uri_func_map;
}

int FTRLDispatcher::PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(-1, "PHXEcho", 1);

    int ret{-1};

    google::protobuf::StringValue req_pb;
    google::protobuf::StringValue resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.PHXEcho(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: PHXEcho = %d", ret);

    return ret;
}

int FTRLDispatcher::FTRL(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(1, "FTRL", 1);

    int ret{-1};

    ftrl::FTRLRequest req_pb;
    ftrl::FTRLResult resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.FTRL(req_pb, &resp_pb);
        }
    }

    // pack response
    {
        if (0 != resp->FromPb(resp_pb)) {
            phxrpc::log(LOG_ERR, "FromPb err %d", ret);

            return -ENOMEM;
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: FTRL = %d", ret);

    return ret;
}

int FTRLDispatcher::Feedback(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp) {
    dispatcher_args_->server_monitor->SvrCall(2, "Feedback", 1);

    int ret{-1};

    ftrl::FTRLFeedback req_pb;
    google::protobuf::Empty resp_pb;

    // unpack request
    {
        ret = req.ToPb(&req_pb);
        if (0 != ret) {
            phxrpc::log(LOG_ERR, "ToPb err %d", ret);

            return -EINVAL;
        }
    }

    // logic process
    {
        if (0 == ret) {
            ret = service_.Feedback(req_pb, &resp_pb);
        }
    }

    phxrpc::log(LOG_DEBUG, "RETN: Feedback = %d", ret);

    return ret;
}

