/* phxrpc_advertisement_tool.cpp

 Generated by phxrpc_pb2tool from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_advertisement_tool.h"

#include "phxrpc/file.h"

#include "advertisement_client.h"


using namespace phxrpc;


AdvertisementTool::AdvertisementTool() {
}

AdvertisementTool::~AdvertisementTool() {
}

int AdvertisementTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int AdvertisementTool::Advertisement(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Advertisement unimplement ***\n");

    return -1;
}

int AdvertisementTool::Feedback(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Feedback unimplement ***\n");

    return -1;
}

