/* phxrpc_ftrl_tool.cpp

 Generated by phxrpc_pb2tool from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_ftrl_tool.h"

#include "phxrpc/file.h"

#include "ftrl_client.h"


using namespace phxrpc;


FTRLTool::FTRLTool() {
}

FTRLTool::~FTRLTool() {
}

int FTRLTool::PHXEcho(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** PHXEcho unimplement ***\n");

    return -1;
}

int FTRLTool::FTRL(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** FTRL unimplement ***\n");

    return -1;
}

int FTRLTool::Feedback(phxrpc::OptMap &/* opt_map */) {
    printf("\n    *** Feedback unimplement ***\n");

    return -1;
}

