/* phxrpc_advertisement_service.h

 Generated by phxrpc_pb2service from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "ftrl.pb.h"


class AdvertisementService {
  public:
    AdvertisementService();
    virtual ~AdvertisementService();

    virtual int PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp);
    virtual int Advertisement(const ftrl::AdvertisementRequest &req, ftrl::AdvertisementResult *resp);
    virtual int Feedback(const ftrl::AdvertisementFeedback &req, google::protobuf::Empty *resp);
};

