/* phxrpc_ftrl_stub.cpp

 Generated by phxrpc_pb2client from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#include "phxrpc_ftrl_stub.h"

#include "phxrpc/http.h"
#include "phxrpc/network.h"
#include "phxrpc/rpc.h"


FTRLStub::FTRLStub(phxrpc::BaseTcpStream &socket, phxrpc::ClientMonitor &client_monitor,
        phxrpc::BaseMessageHandlerFactory &msg_handler_factory)
        : socket_(socket), client_monitor_(client_monitor),
          msg_handler_factory_(msg_handler_factory) {
}

FTRLStub::~FTRLStub() {
}

void FTRLStub::set_keep_alive(const bool keep_alive) {
    keep_alive_ = keep_alive;
}

int FTRLStub::PHXEcho(const google::protobuf::StringValue &req, google::protobuf::StringValue *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/ftrl/PHXEcho", -1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int FTRLStub::FTRL(const ftrl::FTRLRequest &req, ftrl::FTRLResult *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/ftrl/FTRL", 1);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

int FTRLStub::Feedback(const ftrl::FTRLFeedback &req, google::protobuf::Empty *resp) {
    phxrpc::Caller caller(socket_, client_monitor_, msg_handler_factory_);
    caller.set_uri("/ftrl/Feedback", 2);
    caller.set_keep_alive(keep_alive_);
    return caller.Call(req, resp);
}

