/* phxrpc_ftrl_dispatcher.h

 Generated by phxrpc_pb2service from ftrl.proto

 Please DO NOT edit unless you know exactly what you are doing.

*/

#pragma once

#include "phxrpc/rpc.h"


class FTRLService;

class FTRLDispatcher {
  public:
    static const phxrpc::BaseDispatcher<FTRLDispatcher>::URIFuncMap &GetURIFuncMap();

    FTRLDispatcher(FTRLService &service, phxrpc::DispatcherArgs_t *dispatcher_args);

    virtual ~FTRLDispatcher();

    int PHXEcho(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int FTRL(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);
    int Feedback(const phxrpc::BaseRequest &req, phxrpc::BaseResponse *const resp);

  private:
    FTRLService &service_;
    phxrpc::DispatcherArgs_t *dispatcher_args_;
};

